name: mi_card
description: "Lab 2 - MiCard: danh thiếp kỹ thuật số bằng Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-Regular.ttf
    - family: RobotoCondensed
      fonts:
        - asset: fonts/RobotoCondensed-Regular.ttf
